# Generated by Django 5.2.4 on 2025-07-21 06:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('lastmod', models.DateField()),
                ('text', models.TextField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='decisions_d_search__8375b7_gin')],
            },
        ),
    ]
