# Generated by Django 5.2.4 on 2025-07-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Queries'},
        ),
    ]
